In [1]:
import torch


In [2]:
torch.__version__

'2.0.1+cu117'

In [4]:
x = torch.empty([5,3])
x

tensor([[2.4202e+01, 4.5553e-41, 8.2172e-34],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [2.6821e-26, 7.7052e+31, 7.2148e+22],
        [1.5766e-19, 1.0256e-08, 4.2004e-05]])

In [5]:
y = torch.empty(5,3)
y

tensor([[0.0000e+00, 0.0000e+00, 7.7052e+31],
        [7.2148e+22, 1.5766e-19, 1.0256e-08],
        [4.2004e-05, 3.1816e+12, 6.7736e-10],
        [1.6692e-07, 4.3207e-05, 1.2962e+16],
        [2.1707e-18, 7.0952e+22, 1.7748e+28]])

In [6]:
a = torch.rand(5,4)
a

tensor([[0.1672, 0.3335, 0.2623, 0.4452],
        [0.8190, 0.2806, 0.5880, 0.9062],
        [0.4334, 0.7735, 0.8025, 0.0416],
        [0.4169, 0.6597, 0.0905, 0.3503],
        [0.1422, 0.9858, 0.2975, 0.4633]])

In [7]:
z = torch.zeros((5,4), dtype=torch.long)
z

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [8]:
b = torch.tensor([1,2,3])
b

tensor([1, 2, 3])

In [12]:
c = torch.randn_like(z, dtype=torch.float64)
c

tensor([[-2.5253, -1.9676, -0.6383, -1.1611],
        [-1.9770,  0.9374, -1.9958,  0.2015],
        [ 0.4655, -0.1563, -0.5114, -2.1911],
        [-1.6242, -0.8944,  0.5580, -0.4568],
        [ 0.6802, -0.3347, -0.5762,  1.1474]], dtype=torch.float64)

# the value of the defined tensor can be changed in the following way

In [13]:
c = c.new_ones(5,6, dtype = torch.double)
c

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=torch.float64)

# the shapr of the tensor can be found using the size function


In [14]:
print(c.size())

torch.Size([5, 6])


In [15]:
d = torch.rand(5,6,dtype = torch.double)
d

tensor([[0.5784, 0.5149, 0.7025, 0.9634, 0.4591, 0.6317],
        [0.3245, 0.3438, 0.0234, 0.9746, 0.6163, 0.1875],
        [0.3454, 0.4032, 0.8773, 0.0272, 0.6316, 0.9132],
        [0.1836, 0.7207, 0.5240, 0.1618, 0.0968, 0.2839],
        [0.9689, 0.9574, 0.2970, 0.0683, 0.9662, 0.7217]], dtype=torch.float64)

In [18]:
e = torch.randn(5,6, dtype=torch.float)
print(d+e)

tensor([[ 0.7729,  0.3256, -0.0435,  2.3830, -0.0806,  0.2288],
        [ 0.4308,  0.4189,  0.7636,  2.7971, -0.0318,  1.2516],
        [ 0.8287,  1.5061,  0.1967,  1.0386,  2.4447, -0.8434],
        [ 1.2564, -0.4941,  1.0680, -1.3986, -0.2741,  0.5353],
        [ 2.2765,  1.0223, -0.2058,  0.3535,  0.8520, -0.6003]],
       dtype=torch.float64)


## the tensor.view() method is used to reshape teh tensor , it is similar to the reshape function in numpy , the -1 method is used so that we can automatically infer the dimensions

In [20]:
x = torch.randn(4,5)
y = x.view(20)
z = x.view(-1, 2, 2)
print(x, x.size())
print(y, y.size())
print(z, z.size())

tensor([[ 0.2024, -0.1482, -1.1744,  0.0259,  0.4702],
        [ 0.6495, -1.6974,  1.2694,  0.5202, -0.6905],
        [-0.1809,  0.7026, -0.8078, -2.2673, -0.1239],
        [-0.1738, -0.3875, -0.3521,  0.3478,  2.0510]]) torch.Size([4, 5])
tensor([ 0.2024, -0.1482, -1.1744,  0.0259,  0.4702,  0.6495, -1.6974,  1.2694,
         0.5202, -0.6905, -0.1809,  0.7026, -0.8078, -2.2673, -0.1239, -0.1738,
        -0.3875, -0.3521,  0.3478,  2.0510]) torch.Size([20])
tensor([[[ 0.2024, -0.1482],
         [-1.1744,  0.0259]],

        [[ 0.4702,  0.6495],
         [-1.6974,  1.2694]],

        [[ 0.5202, -0.6905],
         [-0.1809,  0.7026]],

        [[-0.8078, -2.2673],
         [-0.1239, -0.1738]],

        [[-0.3875, -0.3521],
         [ 0.3478,  2.0510]]]) torch.Size([5, 2, 2])


## to convert the torch tensor into numpy array the following method is used

In [21]:
print(e.numpy())

[[ 0.1944304  -0.18934357 -0.74602437  1.4195651  -0.5396932  -0.4028598 ]
 [ 0.10628311  0.07502243  0.74026704  1.8225049  -0.6481221   1.0641217 ]
 [ 0.4833503   1.1029056  -0.6806228   1.0114052   1.8130323  -1.7566729 ]
 [ 1.0728288  -1.2148598   0.5440315  -1.5604011  -0.37087864  0.2514362 ]
 [ 1.3076197   0.06487114 -0.5027632   0.28511557 -0.11419692 -1.3220891 ]]


# Autograd -> this is used for computing Gradients and other backward propagation methods

# Creating a simple neural network

In [22]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
# a new class Net is created . It inherits from nn.Module class
class Net(nn.Module):
    def __int__(self):
        super(Net, self).__init__()
