In [45]:
import numpy as np

In [2]:
a = np.array([1,2,3,4], dtype='int16')
print(a)

[1 2 3 4]


In [11]:
b = np.array([[1.0,2.4,3.5],[2.1,4.5,6.3]])
print(b)

[[1.  2.4 3.5]
 [2.1 4.5 6.3]]


In [5]:
# Get the dimension of the numpy array
a.ndim

1

In [6]:
# Get the shape of the numpy array
b.shape

(2, 3)

In [21]:
# Get the data-type
a.dtype

dtype('int64')

In [24]:
# Get the size aka the data it is taking here 8 bytes for the 64 bit
a.itemsize

8

# Adding/Changing specific elements row, col, etc

In [26]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [30]:
# Get a specific element [r,c]
a[1][0]

8

In [33]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
# Get a specific col
a[:, 0]


array([1, 8])

In [35]:
# how to use [start-index : end-index : step-size]
a[1, 1:-2:2]


array([ 9, 11])

# Working with different types of initialization

In [15]:
# how to make all of them zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# for any other number
np.full((2,2),99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [19]:
np.random.rand(2,2)

array([[0.97945901, 0.77162563],
       [0.98601492, 0.20308516]])

In [21]:
np.random.randint(4,7,size=(3,3))

array([[4, 6, 4],
       [5, 5, 4],
       [6, 5, 6]])

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


# Math abilities of numpy

In [27]:
a = np.array([1,2,3])
b = np.array([1,1,1])
print(a)

[1 2 3]


In [28]:
a+2

array([3, 4, 5])

In [30]:
a-2

array([-1,  0,  1])

In [31]:
a*2

array([2, 4, 6])

In [32]:
a/2

array([0.5, 1. , 1.5])

In [33]:
a+b

array([2, 3, 4])

In [36]:
# Take sin of all the values
np.cos(a)
# print(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [37]:
print(a)

[1 2 3]


# After basic maths let's do some linear algebra


In [43]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

# do some statistics (min, max, mean, median, mode, etc...)

In [46]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.min(stats)

1

In [48]:
# to get the min of each row , we can use the axis parameter
np.min(stats, axis=1)

array([1, 4])

In [49]:
# to get the minimum value in each column
np.min(stats, axis = 0)

array([1, 2, 3])

# Reorganiaing arrays
### we can change the shape of the array as long as the no of elements stays the same


In [52]:
before = np.array([[1,2,3,4],[4,5,6,7]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [4 5 6 7]]
[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [57]:
# vertically stack vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v2,v2,v2,v2]))

[[5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


 # Load data from file

In [58]:
np.genfromtxt('data.txt', deletechars=',')

array(nan)

In [59]:
# We can index using a list in numpy
a = np.array([1,2,3,4,5])
a[[0,-2,-1]]

array([1, 4, 5])